### PR TITLE
Add Documentation

### LINKED ISSUE #12: Write better documentation
We should be using better (some!) source code annotations to generate documentation for rustdoc/docs.rs.

### PR DESCRIPTION
**Pull request by TopologicallySpeaking**
Write documentation for everything visible to `cargo doc`. Should resolve #12 .

### CODE REVIEW

**Comment by TopologicallySpeaking** [comment]
I forgot the top-level documentation. I'm busy now, but I can write that later today.

**Comment by toby** [comment]
This is looking great! Happy to merge it now or wait a bit if you want to write the top-level stuff first.

**Comment by TopologicallySpeaking** [comment]
It's ready. I was unexpectedly busy these past few days.

**Comment by toby** [comment]
Thank you for this! Sorry for taking so long to get it out, it's awesome though.

**Pull request merged**
